version: "3"

services:
  nginx:
    build: nginx/
    volumes:
      - ./webroot:/var/www/html
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    depends_on:
      - apache
  apache:
    build: apache/
    volumes:
      - ./webroot:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      - db_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
    ports:
      - "3306:3306"
volumes:
  db_volume:
